---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
    touchscreen:
      pins:
        rx:
          port: "0"
          index: 5
        tx:
          port: "0"
          index: 4
      components: 64
  i2c:
    display:
      pins:
        sda:
          port: "0"
          index: 16
        scl:
          port: "0"
          index: 17
  test: true
